apiVersion: v1
kind: Pod
metadata:
  name: scale-up-nginx1
  labels:
    app: scale-up-nginx1
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: scale-up-nginx2
  labels:
    app: scale-up-nginx2
spec:
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 80
